version: '3'

services:
  app_sgt:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://sgt_db:3306/sgt?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      sgt_db:
          condition: service_healthy
  sgt_db:
    image: mysql:8.0.36 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sgt
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10